# plugins/uberdev/lib/aliases-sync.sh
#
# Shared library for short-form alias installation. SOURCED, never executed.
# No shebang (sourced only); .sh extension (convention).
#
# Public surface:
#   ALIASES                   — array of SHORT|CANON|TOOLS_JSON rows. SSOT.
#   BUILTINS                  — list of Claude Code built-in command names
#                               that must never be overwritten.
#   aliases_sync_main()       — top-level entry; idempotent; always returns 0.
#   aliases_sync_remove()     — companion for /uberdev:uninstall-aliases.
#
# Sourced by:
#   - plugins/uberdev/hooks/session-start (auto-install on session start)
#   - plugins/uberdev/commands/install-aliases.md (manual install)
#
# Known limitation: atomic-rename behaviour (mktemp + mv -f) requires a
# POSIX-compliant filesystem. Network mounts / FUSE may not honour
# atomicity; out of scope for v1 (documented in spec risks table).

# Per-alias config: short-name|canonical-name|JSON-array-of-allowed-tools.
# Must be byte-identical to each canonical's allowed-tools frontmatter
# (enforced by tests/aliases.test.sh:A6).
ALIASES='issue|issue|["Bash", "Glob", "Grep", "Read", "Task"]
solve|solve|["Bash", "Read", "Task"]
turbo|turbo|["Bash", "Read", "Task"]
simplify|simplify|["Bash", "Edit", "Glob", "Grep", "MultiEdit", "Read", "Task", "Write"]
review-pr|review-pr|["Bash(git*)", "Bash(gh*)", "Edit", "Glob", "Grep", "MultiEdit", "Read", "Task", "Write"]
merge|merge|["Bash", "Glob", "Grep", "Read", "Task"]
dev|dev|["Bash", "Read", "Edit", "Write", "Task"]'

# Built-in Claude Code commands; never overwrite these.
BUILTINS='init review security-review statusline-setup help clear plugin'

# _aliases_write_forwarder SHORT CANON TOOLS PLUGIN_ROOT TARGET
# Writes the forwarder body to TARGET via mktemp + mv -f atomic rename.
# All variables double-quoted (security mitigation 1).
_aliases_write_forwarder() {
  local SHORT="$1" CANON="$2" TOOLS="$3" PLUGIN_ROOT="$4" TARGET="$5"
  local CANON_FILE="$PLUGIN_ROOT/commands/${CANON}.md"
  local DEST_DIR
  DEST_DIR="$(dirname "$TARGET")"
  local TMP
  TMP="$(mktemp "$DEST_DIR/.${SHORT}.md.XXXXXX")" || return 1
  { cat > "$TMP" <<EOF
---
description: "Alias for /uberdev:$CANON"
argument-hint: "<args>  # forwarded to /uberdev:$CANON"
allowed-tools: $TOOLS
---

<!-- managed-by: uberdev-aliases -->
<!-- Generated by /uberdev:install-aliases. Remove via /uberdev:uninstall-aliases. -->
<!-- Do not edit by hand — re-run /uberdev:install-aliases --force to regenerate. -->

# /$SHORT — alias for /uberdev:$CANON

This is a top-level shorthand for the canonical \`/uberdev:$CANON\`.
Treat this invocation exactly as if the user had typed
\`/uberdev:$CANON \$ARGUMENTS\`. There is no logic here — the canonical
command file lives in the uberdev plugin install.

- **canonical command**: \`$CANON_FILE\`
- **\${CLAUDE_PLUGIN_ROOT}** (resolved at install time): \`$PLUGIN_ROOT\`
- **user arguments**: \`\$ARGUMENTS\`

**Action:** Read the canonical command file with the \`Read\` tool, then
follow its instructions exactly. Wherever the canonical references
\`\${CLAUDE_PLUGIN_ROOT}\`, substitute the resolved path above. Pass
\`\$ARGUMENTS\` through unchanged.

If the canonical path is stale (e.g. you reinstalled the plugin to a
different location), re-run \`/uberdev:install-aliases --force\` to
regenerate this file.
EOF
  } || { rm -f "$TMP"; return 1; }
  mv -f "$TMP" "$TARGET" || { rm -f "$TMP"; return 1; }
  return 0
}

# _aliases_check_marker TARGET
# Returns 0 if TARGET carries the managed-by marker; 1 otherwise.
# Reads only first 1KB to bound memory; content-based (never filename).
_aliases_check_marker() {
  local TARGET="$1"
  [ -e "$TARGET" ] || return 1
  head -c 1024 "$TARGET" 2>/dev/null | grep -q 'managed-by: uberdev-aliases'
}

# aliases_sync_main
# Idempotent. Always returns 0. Reads:
#   - $PLUGIN_ROOT (must be set by caller)
#   - $UBERDEV_NO_AUTO_ALIAS (env, optional)
#   - $PWD/.claude/uberdev.local.md (file, optional)
aliases_sync_main() {
  # 1. Opt-out gates (env + file). Env wins (precedence: env > file > default).
  case "${UBERDEV_NO_AUTO_ALIAS:-}" in
    1|true|TRUE|yes|YES) return 0 ;;
  esac
  if grep -qE '^auto_install_aliases:[[:space:]]*false[[:space:]]*$' \
       "${PWD}/.claude/uberdev.local.md" 2>/dev/null; then
    return 0
  fi

  # 2. Hard-dep check: jq required to read plugin.json version.
  command -v jq >/dev/null 2>&1 || return 0  # fail-open

  # 3. Plugin-root sanity.
  local PLUGIN_ROOT_LOCAL="${PLUGIN_ROOT:-${CLAUDE_PLUGIN_ROOT:-${CURSOR_PLUGIN_ROOT:-}}}"
  [ -n "$PLUGIN_ROOT_LOCAL" ] || return 0
  [ -f "$PLUGIN_ROOT_LOCAL/.claude-plugin/plugin.json" ] || return 0

  # HOME guard (fail-open under set -u if HOME is unset).
  [ -n "${HOME:-}" ] || return 0
  local DEST_DIR="$HOME/.claude/commands"
  local MARKER="$HOME/.claude/.uberdev-aliases-version"
  local VERSION INSTALLED FIRST_RUN
  VERSION="$(jq -r .version "$PLUGIN_ROOT_LOCAL/.claude-plugin/plugin.json" 2>/dev/null)" || return 0
  [ -n "$VERSION" ] && [ "$VERSION" != "null" ] || return 0

  INSTALLED="$(cat "$MARKER" 2>/dev/null || true)"

  # 4. Idempotency check.
  if [ "$INSTALLED" = "$VERSION" ]; then
    return 0
  fi

  if [ -z "$INSTALLED" ]; then
    FIRST_RUN=1
  else
    FIRST_RUN=0
  fi

  # 5. Realpath/symlink containment guard (security mitigation 3).
  if [ -L "$DEST_DIR" ]; then
    echo "uberdev: ~/.claude/commands is a symlink; refusing to sync" >&2
    return 0
  fi
  mkdir -p "$DEST_DIR" 2>/dev/null || return 0

  # 6. Per-alias loop.
  local INSTALLED_LIST=()
  local SKIPPED_LIST=()
  local FAILED_LIST=()
  local SHORT CANON TOOLS TARGET
  while IFS='|' read -r SHORT CANON TOOLS; do
    [ -n "$SHORT" ] || continue
    TARGET="$DEST_DIR/${SHORT}.md"
    # Built-in protection.
    case " $BUILTINS " in
      *" $SHORT "*) continue ;;
    esac
    # Marker-scoped collision check.
    if [ -e "$TARGET" ] && ! _aliases_check_marker "$TARGET"; then
      SKIPPED_LIST+=("$SHORT")
      continue
    fi
    # Atomic write (per-iteration cleanup is inside _aliases_write_forwarder).
    if _aliases_write_forwarder "$SHORT" "$CANON" "$TOOLS" "$PLUGIN_ROOT_LOCAL" "$TARGET"; then
      INSTALLED_LIST+=("$SHORT")
    else
      FAILED_LIST+=("$SHORT")
    fi
  done <<< "$ALIASES"

  # 7. Atomic version-marker write.
  local MTMP
  MTMP="$(mktemp "$HOME/.claude/.uberdev-aliases-version.XXXXXX")" || return 0
  printf '%s\n' "$VERSION" > "$MTMP"
  mv -f "$MTMP" "$MARKER" || { rm -f "$MTMP"; return 0; }

  # 8. First-run summary line (Q5: only on first install).
  if [ "$FIRST_RUN" = "1" ]; then
    local skipped_str=""
    if [ "${#SKIPPED_LIST[@]}" -gt 0 ]; then
      skipped_str="${SKIPPED_LIST[*]}"
    fi
    local failed_str=""
    if [ "${#FAILED_LIST[@]}" -gt 0 ]; then
      failed_str=", failed ${#FAILED_LIST[@]} (${FAILED_LIST[*]})"
    fi
    echo "first run: installed ${#INSTALLED_LIST[@]} aliases, skipped ${#SKIPPED_LIST[@]} conflicts (${skipped_str})${failed_str}; opt out with UBERDEV_NO_AUTO_ALIAS=1" >&2
  fi
  return 0
}

# aliases_sync_remove
# Removes ~/.claude/.uberdev-aliases-version. Idempotent.
# Forwarder removal stays in commands/uninstall-aliases.md (uses BUILTINS
# marker check for safety); this helper handles only the marker-file part.
aliases_sync_remove() {
  # HOME guard (fail-open under set -u if HOME is unset).
  [ -n "${HOME:-}" ] || return 0
  local MARKER="$HOME/.claude/.uberdev-aliases-version"
  if [ -f "$MARKER" ]; then
    rm -f "$MARKER" && echo "removed $MARKER"
  fi
  return 0
}
